Add Nginx run tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,15 +36,28 @@ jobs:
         with:
           repository: nginx/nginx
           path: nginx
-      - name: Get ngx_devel_kit
-        uses: actions/checkout@v3
-        with:
-          repository: vision5/ngx_devel_kit
-          path: ngx_devel_kit
       - name: Build nginx
         working-directory: nginx
         run: |
           ./auto/configure --with-ld-opt="-Wl,-rpath,/usr/local/lib" --without-pcre2 --add-module=/home/runner/work/ModSecurity-nginx/ModSecurity-nginx/ModSecurity-nginx
           make
+          make modules
           sudo make install
-          /usr/local/nginx/sbin/nginx -V
+          /usr/local/nginx/sbin/nginx -c /home/runner/work/ModSecurity-nginx/ModSecurity-nginx/ModSecurity-nginx/.github/nginx.conf
+      - name: Run attack test vhost 1
+        run: |
+          resp=`curl -I -X GET -H "Host: modsectest1" http://localhost/?q=attack | head -1 | cut -d$' ' -f2`
+          if [ $resp == "403" ]; then echo "OK"; else echo "FAIL"; exit 1; fi
+      - name: Run non-attack test vhost 1
+        run: |
+          resp=`curl -I -X GET -H "Host: modsectest1" http://localhost/?q=1 | head -1 | cut -d$' ' -f2`
+          if [ $resp == "200" ]; then echo "OK"; else echo "FAIL"; exit 1; fi
+      - name: Run attack test vhost 2
+        run: |
+          resp=`curl -I -X GET -H "Host: modsectest2" http://localhost/?q=attack | head -1 | cut -d$' ' -f2`
+          if [ $resp == "403" ]; then echo "OK"; else echo "FAIL"; exit 1; fi
+      - name: Run non-attack test vhost 2
+        run: |
+          resp=`curl -I -X GET -H "Host: modsectest2" http://localhost/?q=1 | head -1 | cut -d$' ' -f2`
+          if [ $resp == "200" ]; then echo "OK"; else echo "FAIL"; exit 1; fi
+
